const ROUTER_PATH = {
   HOME_FIRST: "/",
   LOGIN: "/login",
   TEAM_INFO: "/teamInfo",
   HOME_INDEX: "index",
   HOME_SECOND: "second",
   ABOUT_US: "about-us",
   CONTACT: "contact",
   SCHEDULE: "schedule",
   INVOICE: "invoice",
   BOOKING_TICKET_MANAGER: "booking-ticket-manager",
   NEWS: "tin-tuc",
   BOOKING_TICKET: "booking-ticket",
   PAYMENT: "thanh-toan",
   GUIDE: "huong-dan-dat-ve",
   NEWS_SUMMARY: "tong-hop",
   NEWS_PROMOTION: "khuyen-mai",
   NEWS_AWARD: "giai-thuong",
   NEWS_STOP: "tram-dung",
   NEWS_FUTA_BUS_LINES: "futa-bus-lines",
   NEWS_FUTA_CITY_BUS: "futa-city-bus",
   SUCCESS_PAYMENT: "thanh-toan-thanh-cong",
};
export default ROUTER_PATH;
